### ISSUE TITLE
Reference environment variable as part of string

### ISSUE THREAD

**Issue by estan** [waylan/pyyaml-env-tag#4]
Is it possible to include to reference environment variable within a string?

E.g. something like

```yaml
foo: "bar ${SOME_VARIABLE} baz"
```

**Comment by waylan** [comment]
No, that is not supported. As noted in the [Related](https://github.com/waylan/pyyaml-env-tag?tab=readme-ov-file#related) section of the README, some other solutions have chosen that route, but I have chose a different set of priorities for this solution. There are no plans to provide a solution for the requested feature.

**Comment by estan** [comment]
Ah, apologes for somehow not spotting that, thanks @waylan!
